### ISSUE TITLE
New Histology Vendor and Instrument

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#11]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

Histology

### Describe the change request (use a numbered list if many).

Add acquisition instrument vendor = 'Roche Diagnostics"

Add acquisition instrument model = "Discovery Ultra"

https://diagnostics.roche.com/us/en/products/product-category/immunohistochemistry--ihc-/discovery-ultra.html

No more precise model numbers. These are the serial numbers of the lab's machines: #311185 and #330024

**Comment by HerrLufty** [comment]
Hey @johardi did this ever get pushed into production? A data provider just reported this option was not in the CVS/TSV

I didn't see it either

**Comment by johardi** [comment]
Change to preparation instrument vendor and model
