### ISSUE TITLE
Metadata schema additions for RNAseq (w/ probes) for GeoMX (NGS)

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#14]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

RNAseq (with probes)

### Describe the change request (use a numbered list if many).

add umi_size = 14; **NOTE: hold on this as it may impact pipelines and/or soft assay rules decision engine; [investigating**

add library_preparation_kit
- 10X Genomics; Visium Spatial for FFPE Gene Expression Kit, Mouse Transcriptome, 1 slide, 4 reactions; PN 1000339
Attached (CG000407.pdf, pg. 7)

add sample_indexing_kits
- NanoString Technologies; GeoMx Seq Code Pack; PN GMX-NGS-SEQ-AB Attached (GeoMx_RNA_Flyer.pdf, pg. 4)
- NanoString Technologies; GeoMx Seq Code Pack; PN GMX-NGS-SEQ-CD Attached (GeoMx_RNA_Flyer.pdf, pg. 4)
- NanoString Technologies; GeoMx Seq Code Pack; PN GMX-NGS-SEQ-EF Attached (GeoMx_RNA_Flyer.pdf, pg. 4)
- NanoString Technologies; GeoMx Seq Code Pack; PN GMX-NGS-SEQ-GH Attached (GeoMx_RNA_Flyer.pdf, pg. 4)

add sequencing_reagent_kits
- Illumina; NovaSeq 6000 S1 Reagent v1.5 Kit (200 Cycles); PN 20028318
 [NovaSeq 6000 Reagents link](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.illumina.com%2Fproducts%2Fby-type%2Fsequencing-kits%2Fcluster-gen-sequencing-reagents%2Fnovaseq-reagent-kits.html&data=05%7C02%7CRSM66%40pitt.edu%7C895f6c1f379d44058b2108dc44630812%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C638460439342844666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=H6a%2FQy1kpY71ALTNA2AvtHB7eDHuprYi86QNnVPd3TY%3D&reserved=0)
- Illumina; NextSeq 2000 P3 Reagents Kit (100 Cycles); PN 20040559
 [NextSeq Reagents link](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.illumina.com%2Fproducts%2Fby-type%2Fsequencing-kits%2Fcluster-gen-sequencing-reagents%2Fnextseq-1000-2000-reagents.html&data=05%7C02%7CRSM66%40pitt.edu%7C895f6c1f379d44058b2108dc44630812%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C638460439342850965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=WVWHSClIQ2IJG6%2BeGsvASJg3sg6xQla%2FaMzl1ogzPIA%3D&reserved=0)

add oligo_probe_panels
- 10x Genomics; Visium Mouse Transcriptome Probe Kit - Small; PN 1000365 Attached (CG000407.pdf, pg. 11)
- NanoString Technologies; GeoMx Human Whole Transcriptome Atlas, 4 slides; PN GMX-RNA-NGS-HuWTA-4 Attached (GeoMx_RNA_Flyer.pdf, pg. 4)
- NanoString Technologies; GeoMx Mouse Whole Transcriptome Atlas, 4 slides; PN GMX-RNA-NGS-MsWTA-4 Attached (GeoMx_RNA_Flyer.pdf, pg. 4)

[GeoMx_RNA_Flyer.pdf](https://github.com/hubmapconsortium/dataset-metadata-spreadsheet/files/14607768/GeoMx_RNA_Flyer.pdf)
[CG000407.pdf](https://github.com/hubmapconsortium/dataset-metadata-spreadsheet/files/14607769/CG000407.pdf)

**Comment by johardi** [comment]
Closes with https://github.com/hubmapconsortium/dataset-metadata-spreadsheet/commit/84ac08d6a19352efa34a880f2a13936f2954f7bd
