### ISSUE TITLE
New acquisition instrument vendor and acquisition instrument models

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#15]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

Visium (no probes), Visium (with probes), Histology, CyCIF, Other

### Describe the change request (use a numbered list if many).

Add new acquisition instrument vendor = 'GE Healthcare"

Add new acquisition instrument models:

- Visium CytAssist - Visium (w/probes)and Visium (w/o probes): https://www.10xgenomics.com/instruments/visium-cytassist
- IN Cell Analyzer 2200 - Histology, CyCIF: https://scicrunch.org/resolver/RRID:SCR_023616
- EasyScan One - Histology: https://www.motic.com/As_MoticEasyScan_One1/product_909.html

**Comment by johardi** [comment]
@HerrLufty You also chose "Other" for the target metadata schema. Do you know the specific name of it?

**Comment by HerrLufty** [comment]
I edited it afterwards and should've cleared that

**Comment by johardi** [comment]
The "EasyScan One" model was already registered before but it is called "MoticEasyScan One."

**Comment by HerrLufty** [comment]
OK, let's use that name then

**Comment by johardi** [comment]
Visium dataset doesn't have acquisition instrument vendor and model
