### ISSUE TITLE
New scRNAseq kits

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#16]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

Other

### If 'Other' is selected, please enter the schema name below.

scRNAseq

### Describe the change request (use a numbered list if many).

New library_preparation_kits

- Chromium Next GEM Automated Single Cell 5' Kit v2, 24 rxns PN-1000290
- Chromium Next GEM Automated Single Cell 5' Kit v2, 4 rxns PN-1000298
- Chromium Next GEM Single Cell 5' Kit v2, 16 rxns PN-1000263

New sample_indexing_kit
- Dual Index Kit TT Set A, 96 rxns PN-1000215

New preparation_instrument_kits
- Chromium Next GEM Chip K Single Cell Kit, 48 rxns PN-1000286
- Chromium Next GEM Chip K Single Cell Kit, 16 rxns PN-1000287

**Comment by johardi** [comment]
The next-gen schemas don't have `scRNAseq` type and the option for RNAseq is either `RNAseq (with probes)` or `RNAseq`. Which one is it for this ticket?

**Comment by HerrLufty** [comment]
No probes!

**Comment by johardi** [comment]
**Official names:**

library_preparation_kits

- 10X Genomics; Chromium Next GEM Automated Single Cell 5' Kit v2, 24 rxns; PN 1000290
- 10X Genomics; Chromium Next GEM Automated Single Cell 5' Kit v2, 4 rxns; PN 1000298
- 10X Genomics; Chromium Next GEM Single Cell 5' Kit v2, 16 rxns; PN 1000263

sample_indexing_kit

- 10X Genomics; Dual Index Kit TT, Set A (96 rxn); PN 1000215

preparation_instrument_kits

- 10X Genomics; Chromium Next GEM Chip K Single Cell Kit, 48 rxns; PN 1000286
- 10X Genomics; Chromium Next GEM Chip K Single Cell Kit, 16 rxns; PN 1000287
