### ISSUE TITLE
Add new Barcode Offset for RNAseq

### ISSUE THREAD

**Issue by johardi** [hubmapconsortium/dataset-metadata-spreadsheet#18]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

RNAseq

### Describe the change request (use a numbered list if many).

Add barcode_offset = '10,48,78'

NOTE: This may impact pipeline processing and/or soft assay decision rules engine.

Related to ticket https://github.com/hubmapconsortium/dataset-metadata-spreadsheet/issues/13

**Comment by HerrLufty** [comment]
Hey @johardi, the pipeline is being modified for this, so it can be added now.
