### ISSUE TITLE
New preparation_instrument_kit for RNAseq

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#32]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

RNAseq

### Describe the change request (use a numbered list if many).

Add new preparation_instrument_kit = Chromium Next GEM Chip G Single Cell Kit, 16 rxns (1000127)

**Comment by johardi** [comment]
Closes by https://github.com/hubmapconsortium/dataset-metadata-spreadsheet/commit/2bc42abf8b7ed166588def10c4506fffa8730682
