### ISSUE TITLE
New RNAseq sequencing_reagent_kit

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#34]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

RNAseq

### Describe the change request (use a numbered list if many).

Add new sequencing_reagent_kit = Illumina; NextSeq 500/550 High-output kit (75 Cycles)

**Comment by johardi** [comment]
Could you please confirm with the SME if the kit is referred to "Illumina NextSeq 500/550 High Output Kit 75 Cycles v2.5, PN 20024906"?
