### ISSUE TITLE
RNAseq (w/probes) oligo_probe_panel modifications

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#39]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

RNAseq (with probes)

### Describe the change request (use a numbered list if many).

Remove the following options from oligo_probe_panel field:

- 10x Genomics; Chromium Fixed RNA Kit, Human Transcriptome 4 rxns x 4 BC; PN 1000475
- 10x Genomics; Chromium Fixed RNA Kit, Human Transcriptome 4 rxns x 16 BC; PN 1000476

Add the following options to the oligo_probe_panel field:

- 10x Genomics; Visium Human Transcriptome Probe Kit – Large PN-1000364
- 10X Genomics; Chromium Next GEM Single Cell Fixed RNA Human Transcriptome Probe Kit, 16 rxns; PN 1000420

**Comment by johardi** [comment]
I'm ready to publish the new TSV and Excel files but want to make sure if this is a major change or a minor one?

**Comment by HerrLufty** [comment]
It's technically a major, but we've already reached out to the TMC and changed the data behind the scenes.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
