### ISSUE TITLE
New acquisition instrument for H&E

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#4]
Please add Leica Biosystems Aperio AT2 for to H&E acquisition instruments.

No longer manufacturer by Leica...here's a reseller link

https://www.medicalexpo.com/prod/leica-biosystems/product-95735-653510.html

Let me know if you have any questions.

Richard

**Comment by johardi** [comment]
I found the instrument model is already in the RRID database, so I'll just reuse it:

https://scicrunch.org/resolver/RRID:SCR_021256

**Comment by HerrLufty** [comment]
Cool
