### ISSUE TITLE
New acquisition_instrument_vendor for Histology

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#42]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

Histology

### Describe the change request (use a numbered list if many).

Add new acquisition_instrument_vendor = 'Olympus'

Model is already in acquisition_instrument_model drop-down

**Comment by johardi** [comment]
Olympus has rebranded as Evident Scientific (see: https://www.evidentscientific.com/en/). I have labeled the term as "[Evident Scientific (Olympus)](https://bioportal.bioontology.org/ontologies/HRAVS/?p=classes&conceptid=https%3A%2F%2Fidentifiers.org%2FRRID%3ASCR_024782&jump_to_nav=true)" to make it more explicit.

**Comment by HerrLufty** [comment]
I thought we decided that, when there was a rebranding, we would still use the name of the device to avoid confusion.

**Comment by HerrLufty** [comment]
Well, if it has to be, it has to be. The data provider was pretty crabby about the fact that their instrument model was available, but the vendor wasn't available, at least not clearly.

**Comment by johardi** [comment]
Understood. But they need to accept that the brand Olympus no longer exists for scientific instruments. The name is now Evident Scientific and using Olympus would be misleading. If the data providers are still curious, refer them to the FAQ page (https://www.evidentscientific.com/en/faq/) which explains that both names refer to the same business entity. I hope this clears up any confusion and they accept the name change.

I'm going to close this ticket but feel free to reopen if the issue still persists.
