### ISSUE TITLE
New preparation_medium and storage_medium for LC-MS

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#44]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

LC-MS

### Describe the change request (use a numbered list if many).

Add 'HPMC-PVP' to preparation_medium and storage_medium

**Comment by johardi** [comment]
I just realized, LC-MS doesn't have preparation_medium and storage_medium fields. They are only relevant for sample schema.

**Comment by HerrLufty** [comment]
Superceded by #46
