### ISSUE TITLE
MERFISH

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#47]
### What is the schema name?

MERFISH

### Share the Google Sheets URL to the metadata schema with a read access.

https://docs.google.com/spreadsheets/d/1kd1UQ2il-eW-MTM4iEotyAxa8M_hcwn8yQJTU_II-F8/edit?gid=1856663792#gid=1856663792

### Share the Google Sheets URL to the directory structure with a read access.

https://docs.google.com/spreadsheets/d/1LE-iyY2E6eP4E8jhgP6rhsvjESrdHXWYrMwKTvNkI5Y/edit?gid=656581338#gid=656581338

**Comment by johardi** [comment]
@jpuerto-psc 
Initial release MERFISH

| name | metadata_schema_id | version |
| --- | --- | --- |
| merfish | f1ef260f-d4a3-43db-a739-49b394aeee20 | v2.0.0 |

CEDAR OpenView: https://openview.metadatacenter.org/templates/https:%2F%2Frepo.metadatacenter.org%2Ftemplates%2Ff1ef260f-d4a3-43db-a739-49b394aeee20

**Comment by jpuerto-psc** [comment]
Closed by https://github.com/hubmapconsortium/ingest-validation-tools/pull/1346
