### ISSUE TITLE
New optional categorical field (channel quality) in .ome-tiff.channels.csv

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#55]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

Other

### If 'Other' is selected, please enter the schema name below.

.ome-tiff.channels.csv

### Describe the change request (use a numbered list if many).

Field name: channel quality
Field type: categorical
Definition: This is a rough metric of the quality of the individual channel within the image. If any channels are denoted as "poor" quality, then the reason for including the poor channel(s) must be noted in the abstract for this dataset.
Options: Optional
Values: good, fair, poor

**Comment by johardi** [comment]
Added in HRAVS v2.6.0
