### ISSUE TITLE
New oligo_probe_panel for RNAseq (w/ probes)

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#58]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

RNAseq (with probes)

### Describe the change request (use a numbered list if many).

Add the following oligo_probe_panel to RNAseq (w/ probes): 10X Genomics; Chromium Next GEM Single Cell Fixed RNA, Mouse Transcriptome Probe Kit, 64 rxns; PN 1000492

**Comment by johardi** [comment]
Rename to `10x Genomics; Chromium Next GEM Single Cell Fixed RNA Mouse Transcriptome Probe Kit, 64 rxns; PN 1000492`
