### ISSUE TITLE
RNAseq (with probes) Metadata Schema revision

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#6]
### Select the target metadata schema name, or choose 'Other' if not listed.

RNAseq (with probes)

### Describe the change request (use a numbered list if many).

For library_input_unit_amount add option of "ul"

I'm guessing this option should be added to RNAseq and ATAQseq, but will defer to Stephen

**Comment by johardi** [comment]
Closes with https://github.com/hubmapconsortium/dataset-metadata-spreadsheet/commit/cf0b646329a502680f7bc95722b972fe659afbfc
