### ISSUE TITLE
New oligo_probe_panel for Xenium

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#60]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

Xenium

### Describe the change request (use a numbered list if many).

New oligo_probe_panel: 10x Genomics; Xenium Human Multi-Tissue and Cancer Panel, v1; PN 1000626.

Since this is the first for Xenium (I think) I don't believe we have a format yet. Here is some additional info:

[PN info](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.10xgenomics.com%2Fsupport%2Fsoftware%2Fxenium-panel-designer%2Flatest%2Ftutorials%2Fpanel-part-numbers%2Fpre-designed-xenium-v1-parts&data=05%7C02%7CRSM66%40pitt.edu%7C629e9707116b4ad1d7f508dd1616dd45%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C638691009641984049%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=0oSZnb%2BLLbksSu%2Bb3y%2B%2FfzurHuhyJnfxYsStDZAcqIg%3D&reserved=0)

Also, it targets [377 genes](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.10xgenomics.com%2Fsupport%2Fsoftware%2Fxenium-panel-designer%2Flatest%2Ftutorials%2Fpre-designed-xenium-v1&data=05%7C02%7CRSM66%40pitt.edu%7C629e9707116b4ad1d7f508dd1616dd45%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C638691009642006484%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=%2F2KxW2olLAIudKZx7J82F0OTRZFXkfopKuB%2ByMkccFM%3D&reserved=0)

Let me know what you think or if you need anything else.

**Comment by johardi** [comment]
Looks good to me. Minor change is I will omit the comma before the version number.

```
10x Genomics; Xenium Human Multi-Tissue and Cancer Panel v1; PN 1000626
```

**Comment by HerrLufty** [comment]
Sounds good, thanks.
