### ISSUE TITLE
New preparation_instrument_kit for RNAseq

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#61]
### Select the target metadata schema name (can be multiple), or choose 'Other' if not listed.

RNAseq, RNAseq (with probes)

### Describe the change request (use a numbered list if many).

Add new preparation_instrument_kit = 'Chromium GEM-X Single Cell 3' Kit v4 16 rxns PN-1000691'

Additional info [here (page 1)](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.10xgenomics.com%2Fsupport%2Fsingle-cell-gene-expression%2Fdocumentation%2Fsteps%2Flibrary-prep%2Fchromium-gem-x-single-cell-3-v4-gene-expression-user-guide&data=05%7C02%7Crsm66%40pitt.edu%7C3cd40507151a46d5d0d708dd1a00b404%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C638695312518862473%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=eKB37hj6j%2FFKBLf%2FvCwKiLQp2yj6lIRhXWloLxWDP%2F0%3D&reserved=0):

**Comment by johardi** [comment]
Added as `10x Genomics; Chromium GEM-X Single Cell 3' Kit v4, 16 rxns; PN 1000691`
