### ISSUE TITLE
New Histology acquisition_instrument_model to be added

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#7]
### Select the target metadata schema name, or choose 'Other' if not listed.

Histology

### Describe the change request (use a numbered list if many).

please add the following Histology acquisition_instrument_model: EVOS M7000

Manufacturer: Thermo Fisher Scientific

https://www.thermofisher.com/order/catalog/product/AMF7000

**Comment by johardi** [comment]
Requesting the RRID for the instrument model.

**Comment by HerrLufty** [comment]
Data provider is reporting this instrument not available on new version. I confirmed.

**Comment by johardi** [comment]
This model is in the acquisition instrument category. Should it be in the preparation instrument instead?

**Comment by HerrLufty** [comment]
Yes
