### ISSUE TITLE
New RNAseq barcode_offset and umi_offset values

### ISSUE THREAD

**Issue by HerrLufty** [hubmapconsortium/dataset-metadata-spreadsheet#8]
### Select the target metadata schema name, or choose 'Other' if not listed.

RNAseq

### Describe the change request (use a numbered list if many).

add barcode_offset = 20
add umi_offset = 36

**Comment by johardi** [comment]
This change also affects "RNAseq (with probes)" and "ATACseq" as they share the same fields.
